/** @file RNAup.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.22.6
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt by Lorenzo Bettini */

#ifndef RNAUP_H
#define RNAUP_H

double RNAup(int argc, char *argv[], char* seq, int region, int end_pos);

#endif /* RNAUP_H */
